name: Test (pytest)
on:
  push:
    branches:
      - main
      - develop
  pull_request:
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-suffix: "uv_cache"
      - name: Install dependencies
        run: uv sync
      - name: Run tests
        run: |
          set -o pipefail
          uv run pytest tests --junitxml=pytest.xml --cov=src --cov-report=term-missing | tee pytest-coverage.txt
      - name: Add test coverage comment
        # Alternative for open source projects: https://github.com/codecov/example-python
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml
